### ISSUE TITLE
Le fichier financial_token.jwt est manquant

### ISSUE THREAD

**Issue by corebreaker** [nbeguier/financial-tools#4]
A l'exécution, le programme a besoin de ce fichier: `financial_token.jwt`
Un message d'erreur qu'il est manquant.

Comment l'obtenir ?

**Comment by nbeguier** [comment]
Bonjour !

Ce token est généré automatiquement, pas besoin de le créer soi-même. Quelle est l'erreur exactement ?

**Comment by corebreaker** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '\\tmp\\financial_token.jwt'
```

**Comment by corebreaker** [comment]
Ah ok, c'est bon, finalement oui il est bien généré, ça fonctionne.

Merci.
